# Generated by Django 5.0.6 on 2024-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=255)),
                ('features', models.JSONField(verbose_name=models.CharField(max_length=255))),
            ],
        ),
    ]
