# Generated by Django 5.0.6 on 2024-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(),
        ),
    ]
