# Generated by Django 5.0.6 on 2024-07-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_hero_image_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
