# Generated by Django 5.0.6 on 2024-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_contact_portofolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(default='default.jpg', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
