# Generated by Django 5.0.6 on 2024-07-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_heroactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroactive',
            old_name='hero',
            new_name='hero_id',
        ),
    ]
