# Generated by Django 5.0.6 on 2024-07-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_rename_hero_heroactive_hero_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroactive',
            old_name='hero_id',
            new_name='hero',
        ),
    ]
