# Generated by Django 5.0.6 on 2024-07-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_rename_hero_id_heroactive_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroActive',
        ),
    ]
