# Generated by Django 5.0.6 on 2024-07-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_heroactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.AddField(
            model_name='hero',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
