# Generated by Django 5.0.6 on 2024-07-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_remove_hero_image_hero_isactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroActive',
        ),
    ]
