# Generated by Django 5.0.6 on 2024-07-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_delete_heroactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='isActive',
        ),
    ]
