# Generated by Django 5.0.6 on 2024-07-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_remove_hero_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
