# Generated by Django 5.0.6 on 2024-07-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_hero_isactive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Home',
        ),
    ]
