# Generated by Django 5.0.6 on 2024-07-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_rename_hero_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='isActive',
        ),
    ]
