# Generated by Django 5.0.6 on 2024-07-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='images/'),
        ),
    ]
